apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: suggestions.kubeflow.org
spec:
  group: kubeflow.org
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
      - jsonPath: .status.conditions[-1:].type
        name: Type
        type: string
      - jsonPath: .status.conditions[-1:].status
        name: Status
        type: string
      - jsonPath: .spec.requests
        name: Requested
        type: string
      - jsonPath: .status.suggestionCount
        name: Assigned
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: Suggestion
    singular: suggestion
    plural: suggestions
    categories:
      - all
      - kubeflow
      - katib
