apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trials.kubeflow.org
spec:
  group: kubeflow.org
  versions:
    - name: v1beta1
      served: true
      storage: true
      additionalPrinterColumns:
      - jsonPath: .status.conditions[-1:].type
        name: Type
        type: string
      - jsonPath: .status.conditions[-1:].status
        name: Status
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
  scope: Namespaced
  subresources:
    status: {}
  names:
    kind: Trial
    singular: trial
    plural: trials
    categories:
      - all
      - kubeflow
      - katib
